/// cm3 of material matter per sheet
#define MINERAL_MATERIAL_AMOUNT 2000

#define ONE_SHEET MINERAL_MATERIAL_AMOUNT // 2000
#define HALF_SHEET (MINERAL_MATERIAL_AMOUNT*0.5) // 1000
#define QUARTER_SHEET (MINERAL_MATERIAL_AMOUNT*0.25) // 500
